################################################
#   Docker Kép építése és feltöltése ACR-be
################################################
# Szükséges változók:
# ACR_LOGIN_URL - Az Azure Container Registry bejelentkezési URL-je (pl. myregistry.azurecr.io)
# ACR_USERNAME - Az Azure Container Registry felhasználóneve
# Szükséges titkok:
# ACR_PASSWORD - Az Azure Container Registry jelszava (titokként tárolva) 
################################################
name: Docker Kép építése és feltöltése ACR-be
on:
  push:
    branches:
      - main
      - demo

jobs:
  docker:
    name: Build and Push Docker Image to ACR
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v5
      - uses: benjlevesque/short-sha@v3.0
        id: short-sha
        with:
          length: 8
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          registry: ${{ vars.ACR_LOGIN_URL }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ vars.ACR_LOGIN_URL }}/tanulo-42343:latest
            ${{ vars.ACR_LOGIN_URL }}/tanulo-42343:${{ steps.short-sha.outputs.sha }}
